name: ${project.name}
description: ${project.description}
main: com.johnymuffin.beta.ipaccountlimiter.IPAccountLimiter
author: JohnyMuffin
softdepend: [EvolutionCore]
commands:
  ipremove:
    description: Remove record of all usernames from IP
permissions:
  ipaccountlimiter.remove:
    description: Permission for remove ip info